# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['bridge/server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('bridge', 'bridge'),
        ('agent', 'agent'),
        ('api', 'api'),
        ('config', 'config'),
    ],
    hiddenimports=[
        'langgraph',
        'langgraph.checkpoint.memory',
        'anthropic',
        'openai',
        'sse_starlette',
        'sse_starlette.sse',
        'networkx',
        'pydantic_settings',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.protocols',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='agentic-server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
