import { useState } from 'react'
import { Copy, Check, ChevronDown } from 'lucide-react'
import { cn } from '@/lib/cn'

interface TestCase {
  name: string
  code: string
}

interface TestCaseViewerProps {
  tests: TestCase[]
}

function TestCaseItem({ test }: { test: TestCase }) {
  const [expanded, setExpanded] = useState(false)
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(test.code)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // clipboard may not be available
    }
  }

  return (
    <div className="rounded border border-white/8 overflow-hidden">
      <button
        type="button"
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center gap-2 px-3 py-2 text-left text-xs hover:bg-white/5 transition-colors"
      >
        <ChevronDown
          className={cn('w-3.5 h-3.5 text-text-muted transition-transform', expanded && 'rotate-180')}
        />
        <span className="font-medium flex-1">{test.name}</span>
        <span className="text-text-muted">{test.code.length} chars</span>
      </button>

      {expanded && (
        <div className="border-t border-white/8">
          <div className="relative">
            <pre className="p-3 text-xs font-mono overflow-x-auto whitespace-pre bg-surface-overlay max-h-48 overflow-y-auto">
              {test.code}
            </pre>
            <button
              type="button"
              onClick={handleCopy}
              className="absolute top-2 right-2 flex items-center gap-1 px-2 py-1 rounded text-[11px] bg-white/10 hover:bg-white/20 text-text-secondary transition-colors"
            >
              {copied ? (
                <>
                  <Check className="w-3 h-3 text-status-running" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="w-3 h-3" />
                  Copy
                </>
              )}
            </button>
          </div>
        </div>
      )}
    </div>
  )
}

export function TestCaseViewer({ tests }: TestCaseViewerProps) {
  if (tests.length === 0) {
    return <p className="text-xs text-text-muted py-4 text-center">No test cases available.</p>
  }

  return (
    <div className="space-y-1.5">
      <p className="text-xs text-text-muted">
        {tests.length} test case{tests.length !== 1 ? 's' : ''} generated by Reviewer
      </p>
      {tests.map((test, i) => (
        <TestCaseItem key={`${test.name}-${i}`} test={test} />
      ))}
    </div>
  )
}
